name: Unit-Tests

on: [pull_request]

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

#      - name: Cache SonarQube packages
#        uses: actions/cache@v1
#        with:
#          path: ~/.sonar/cache
#          key: ${{ runner.os }}-sonar
#          restore-keys: ${{ runner.os }}-sonar
#
#      - name: Cache Maven packages
#        uses: actions/cache@v1
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2

      - name: Clean
        run: mvn --batch-mode clean

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

      - name: Generate Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit-Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

#      - name: Add coverage to PR
#        id: jacoco
#        uses: madrapps/jacoco-report@v1.3
#        with:
#          paths: target/site/jacoco/jacoco.xml
#          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 5
#          min-coverage-changed-files: 5